<?php
/**
 * Created by PHPStrom.
 * User: Wencai
 * Date: 2017/11/2
 * Time: 10:19
 */
namespace zunxiang\fenlei\actions\sort;

use yii;
use zunxiang\fenlei\actions\BaseAction;
use zunxiang\fenlei\modelsext\SiteConfig;
use zunxiang\fenlei\modelsext\Activity;
use zunxiang\fenlei\modelsext\Forum;
use zunxiang\fenlei\tools\Tool;

class GetSortListAction extends BaseAction{

    public $fids;

    public function beforeRun()
    {
        return parent::beforeRun(); // TODO: Change the autogenerated stub
    }

    public function run(){
        //新 分类信息 页面


        //首页广告
        $top_ad = Activity::getIndexTopAd();
        //板块
        $forumInfo = [];
        //帖子列表+ 广告
        $threadList = [];
        $threadList['ad'] = [];
        //获取小后台配置 VIRTUAL_SORT_SETTING
        $sort_setting = SiteConfig::getVal('VIRTUAL_SORT_SETTING');
        $forums_id = json_decode($sort_setting);
        if(!empty($forums_id)){
            //板块列表  按照顺序
            $forums = Forum::find()
                ->where(['IN','fid',$forums_id])
                ->andWhere(['>','status',0])
                ->indexBy('fid')
                ->asArray()
                ->all();

            foreach($forums_id as $fid){
                $forumInfo[]['fid'] = $forums[$fid]['fid'];
                $forumInfo[]['fname'] = $forums[$fid]['fname'];
                $forumInfo[]['direct_url'] = $forums[$fid]['direct_url'];
                $forumInfo[]['logo'] = $forums[$fid]['logo'];
                $forumInfo[]['default_fname'] = $forums[$fid]['default_fname'];
            }

            //帖子列表  增加广告位，按照发布时间排
            $fids = implode(',',$forums_id);
            $postParams = [
                'action'=>'GetThreadsByFid',
                'fids'=>$fids,
                'ordertype'=>1,     //排序方式  1 发帖日期倒序 0 最后回复时间倒序
                'offset'=>0,
                'limit'=>10
            ];
            $responseString = Tool::request($postParams);
            $response = json_decode($responseString);

            if (!empty($response) && !empty($response['data'])) {
                $threads = $response['data'];
                foreach($threads as $thread){
                    $temp = [];
                    foreach($thread as $val){
                        $temp['tid'] = $val['tid'];
                        $temp['tid'] = $val['tid'];
                    }
                    $threadList['thread'][] = $temp;
                }

            }
            $tpl = 'sort/index.html';
            $html = Yii::$app->getView()->render($tpl,[
                'top_ad'=>$top_ad,
                'forum_info'=>$forumInfo,
                'threads'=>$threadList
            ]);

        }


    }
}