<?php
/**
 * Created by PHPStrom.
 * User: Wencai
 * Date: 2017/11/7
 * Time: 17:31
 */

namespace zunxiang\fenlei\actions\sort;

use yii;
use zunxiang\fenlei\actions\BaseAction;
use zunxiang\fenlei\tools\Tool;

class UpRefreshAction extends BaseAction{

    public $fids;
    public $page;

    public function beforeRun()
    {
        return parent::beforeRun(); // TODO: Change the autogenerated stub
    }

    public function run(){
        $threadList = [];
        if(!empty($this->fids)){
            $postParams = [
                'action'=>'getThreadsByFid',
                'fids'=>$this->fids,
                'ordertype'=>1,     //排序方式  1 发帖日期倒序 0 最后回复时间倒序
                'offset'=>$this->page * 10,
                'limit'=>10
            ];

            $responseString = Tool::request($postParams);

            $response = json_decode($responseString,true);

            if (!empty($response) && !empty($response['data']) && $response['errCode'] == 0 ) {
                $threads = $response['data'];
                foreach($threads as $val){
                    $thread = [];
                    $thread['tid'] = $val['tid'];
                    $thread['subject'] = $val['subject'];
                    $thread['attnum'] = $val['attnum'];
                    $thread['attachs'] = $val['attachs'];
                    $thread['author'] = $val['author'];
                    $thread['views'] = Tool::View_CN($val['hits']);
                    $thread['time'] = Tool::Time_CN($val['postdate']);

                    $threadList[] = $thread;
                }

            }
            $threadList = Tool::_convert($threadList);

            $tpl = '/sort/morethread.php';
            $html = Yii::$app->getView()->render($tpl,[
                'threads'=>$threadList
            ]);

            return $html;
        }


    }
}