<?php
/**
 * Created by PHPStrom.
 * User: Wencai
 * Date: 2017/11/2
 * Time: 10:00
 */

namespace zunxiang\fenlei\controllers;

use yii;
use yii\web\controller;

class BaseController extends Controller{

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
